[package]
name = "djangofmt_formatter"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
repository.workspace = true
license.workspace = true
publish = false

[lib]
doctest = false

[dependencies]
anyhow = { workspace = true }
clap = { workspace = true, optional = true }
djangofmt_syntax = { workspace = true }
dprint-plugin-json = { workspace = true }
dprint-plugin-typescript = { workspace = true }
malva = { workspace = true }
markup_fmt = { workspace = true }
serde = { workspace = true }
tracing = { workspace = true }

[dev-dependencies]
rstest = { workspace = true }
tracing-test = { workspace = true }

[features]
clap = ["dep:clap", "djangofmt_syntax/clap"]

[lints]
workspace = true
