//! Linting for Django/Jinja templates.
//!
//! This crate provides lint rules for HTML templates with Django/Jinja syntax.
//! It works on top of the AST generated by `markup_fmt`.
//!
//! # Example
//!
//! ```
//! use djangofmt_lint::{check_ast, Settings};
//! use markup_fmt::{Language, parser::Parser};
//!
//! let source = r#"<form method="put"></form>"#;
//! let mut parser = Parser::new(source, Language::Jinja, vec![]);
//! let ast = parser.parse_root().unwrap();
//!
//! let diagnostics = check_ast(source, &ast, &Settings::default());
//! assert_eq!(diagnostics.len(), 1);
//! ```

mod checker;
pub mod fix;
pub mod lint_context;
mod noqa;
pub mod registry;
mod rules;
pub mod settings;
mod violation;

pub use checker::Checker;
pub use fix::apply::{
    AppliedFix, ApplyResult, FixerError, FixerResult, MAX_FIX_ITERATIONS, RuleFixSummary,
    SourceMap, SourceMarker, apply_fixes, fix_ast, lint_fix,
};
pub use fix::{Applicability, Edit, Fix, FixAvailability, IsolationLevel};
pub use lint_context::{DiagnosticGuard, LintContext};
pub use registry::{Rule, RuleCategory};
pub use settings::Settings;

use markup_fmt::ast::Root;
use miette::{Diagnostic, NamedSource, SourceSpan};

/// A single lint diagnostic without source code.
///
/// Source code is added later via [`FileDiagnostics`] to avoid cloning
/// the entire file content for each diagnostic.
#[derive(Debug, Clone, Diagnostic, thiserror::Error)]
#[error("{message}")]
pub struct LintDiagnostic {
    /// Rule code (e.g., "invalid-attr-value").
    #[diagnostic(code)]
    pub code: String,
    /// Human-readable error message.
    pub message: String,
    /// Source span where the error occurred.
    #[label("here")]
    pub span: SourceSpan,
    /// Optional help text with suggestions.
    #[help]
    pub help: Option<String>,
    /// Optional fix attached to the diagnostic.
    ///
    /// Stored on the diagnostic; applicability gating happens at apply time.
    pub fix: Option<Fix>,
    /// Optional short imperative summary of the fix.
    ///
    /// Stored separately from `help` so the renderer can mark it as fix-related
    /// (and so a rule's `help()` and `fix_title()` don't fight for the same field).
    pub fix_title: Option<String>,
}

/// A collection of lint diagnostics for a single file.
///
/// This struct holds the source code once and references it for all diagnostics,
/// avoiding the need to clone the source for each individual diagnostic.
#[derive(Debug, Clone, Diagnostic, thiserror::Error)]
#[error("Found {} lint error(s)", self.related.len())]
pub struct FileDiagnostics {
    /// The source code of the file.
    #[source_code]
    pub source_code: NamedSource<String>,
    /// All diagnostics found in this file.
    #[related]
    pub related: Vec<LintDiagnostic>,
}

impl FileDiagnostics {
    /// Create a new `FileDiagnostics` from source code and diagnostics.
    #[must_use]
    pub const fn new(source_code: NamedSource<String>, diagnostics: Vec<LintDiagnostic>) -> Self {
        Self {
            source_code,
            related: diagnostics,
        }
    }

    /// Create a new empty `FileDiagnostics`.
    #[must_use]
    pub fn empty() -> Self {
        Self {
            source_code: NamedSource::new("", String::new()),
            related: vec![],
        }
    }

    /// Returns true if there are no diagnostics.
    #[must_use]
    pub const fn is_empty(&self) -> bool {
        self.related.is_empty()
    }

    /// Returns the number of diagnostics.
    #[must_use]
    pub const fn len(&self) -> usize {
        self.related.len()
    }
}

/// Check the AST for lint errors.
///
/// Traverses the AST and runs all enabled lint rules, then applies
/// `{# noqa #}` suppression as a post-pass — mirrors ruff's pipeline
/// (`crates/ruff_linter/src/linter.rs`: rules emit → `check_noqa` filters).
#[must_use]
pub fn check_ast(source: &str, ast: &Root<'_>, settings: &Settings) -> Vec<LintDiagnostic> {
    let mut checker = Checker::new(source, settings);
    checker.visit_root(ast);
    let mut diagnostics = checker.into_diagnostics();
    noqa::check_noqa(&mut diagnostics, source, ast);
    diagnostics
}
