//! Linting for Django/Jinja templates.
//!
//! This crate provides lint rules for HTML templates with Django/Jinja syntax.
//! It works on top of the AST generated by `markup_fmt`.
//!
//! # Example
//!
//! ```ignore
//! use djangofmt_lint::check_ast;
//! use markup_fmt::{Language, parser::Parser};
//!
//! let source = r#"<form method="put"></form>"#;
//! let mut parser = Parser::new(source, Language::Jinja, vec![]);
//! let ast = parser.parse_root().unwrap();
//!
//! let diagnostics = check_ast(source, &ast);
//! assert_eq!(diagnostics.len(), 1);
//! ```

mod checker;
mod rules;

pub use checker::Checker;

use markup_fmt::ast::Root;
use miette::{Diagnostic, SourceSpan};

/// A lint diagnostic with source location and help text.
///
/// Implements `miette::Diagnostic` for rich error display with source context.
#[derive(Debug, Diagnostic, thiserror::Error)]
#[error("{message}")]
pub struct LintDiagnostic {
    /// The source code being linted (needed for miette to display context).
    #[source_code]
    pub source_code: String,
    /// Rule code (e.g., "E001").
    pub code: &'static str,
    /// Human-readable error message.
    pub message: String,
    /// Source span where the error occurred.
    #[label("{label}")]
    pub span: SourceSpan,
    /// Label shown inline with the source.
    pub label: String,
    /// Optional help text with suggestions.
    #[help]
    pub help: Option<String>,
}

/// Check the AST for lint errors.
///
/// Traverses the AST and runs all enabled lint rules, returning any diagnostics found.
#[must_use]
pub fn check_ast(source: &str, ast: &Root<'_>) -> Vec<LintDiagnostic> {
    let mut checker = Checker::new(source);
    checker.visit_root(ast);
    checker.into_diagnostics()
}
