//! Linting for Django/Jinja templates.
//!
//! This crate provides lint rules for HTML templates with Django/Jinja syntax.
//! It works on top of the AST generated by `markup_fmt`.
//!
//! # Example
//!
//! ```
//! use djangofmt_lint::{lint_source, Settings};
//! use markup_fmt::Language;
//!
//! let source = r#"<form method="put"></form>"#;
//! let diagnostics = lint_source(source, Language::Jinja, &[], &Settings::default(), None).unwrap();
//! assert_eq!(diagnostics.len(), 1);
//! ```

mod checker;
pub mod fix;
pub mod lint_context;
pub mod registry;
pub mod rule_selector;
pub mod rule_set;
mod rules;
pub mod settings;
mod suppression;
mod violation;

pub use checker::Checker;
pub use fix::apply::{
    AppliedFix, ApplyResult, FixerError, FixerResult, MAX_FIX_ITERATIONS, RuleFixSummary,
    apply_fixes, fix_ast, lint_fix,
};
pub use fix::{Applicability, Edit, Fix, FixAvailability, IsolationLevel};
pub use lint_context::{DiagnosticGuard, LintContext};
pub use registry::{Rule, RuleCategory, RuleGroup};
pub use rule_selector::{RuleSelector, SelectionWarning, SelectorParseError};
pub use rule_set::RuleSet;
pub use settings::{LintConfiguration, Settings};
pub use suppression::{FileIgnores, IGNORE_DIRECTIVE, ReservedCode};
pub use violation::{Violation, ViolationMetadata};

use std::borrow::Cow;
use std::path::Path;

use markup_fmt::ast::Root;
use markup_fmt::parser::Parser;
use markup_fmt::{Language, SyntaxError};
use miette::{Diagnostic, GraphicalReportHandler, GraphicalTheme, NamedSource, Report, SourceSpan};
use std::fmt;
use std::sync::{Arc, LazyLock};

/// Narrow a `usize` byte offset or length to the `u32` `oxc-miette` stores.
///
/// Files larger than 4 GiB are not a supported input, so this saturates.
#[must_use]
pub fn clamp_offset(value: usize) -> u32 {
    u32::try_from(value).unwrap_or(u32::MAX)
}

/// A UTF-8 BOM is not Rust whitespace, so strip it explicitly.
#[must_use]
pub(crate) fn strip_bom(source: &str) -> &str {
    source.strip_prefix('\u{feff}').unwrap_or(source)
}

/// Wrap help and note text without splitting URLs.
/// `textwrap` treats `/` and `-` as break opportunities, so a URL is not one word.
#[must_use]
pub fn graphical_handler(theme: GraphicalTheme) -> GraphicalReportHandler {
    GraphicalReportHandler::new_themed(theme)
        .with_word_separator(textwrap::WordSeparator::AsciiSpace)
        .with_word_splitter(textwrap::WordSplitter::NoHyphenation)
        .with_break_words(false)
}

/// Build a [`SourceSpan`] from `usize` byte offsets.
///
/// For a span covering a slice of the source, use [`LintContext::source_span`] instead:
#[must_use]
pub fn span(start: usize, len: usize) -> SourceSpan {
    SourceSpan::new(clamp_offset(start).into(), clamp_offset(len))
}

/// A single lint diagnostic without source code.
///
/// Source code is attached at render time by [`FileDiagnostics::reports`].
#[derive(Debug, Clone, Diagnostic, thiserror::Error)]
#[error("{message}")]
pub struct LintDiagnostic {
    /// Rule code (e.g., "invalid-attr-value").
    #[diagnostic(code)]
    pub code: &'static str,
    /// Human-readable error message.
    pub message: Cow<'static, str>,
    /// Source span where the error occurred.
    #[label("here")]
    pub span: SourceSpan,
    /// Optional help text with suggestions.
    #[help]
    pub help: Option<Cow<'static, str>>,
    /// Optional fix attached to the diagnostic.
    ///
    /// Stored on the diagnostic; applicability gating happens at apply time.
    pub fix: Option<Fix>,
    /// Optional short imperative summary of the fix.
    ///
    /// Stored separately from `help` so the renderer can mark it as fix-related
    /// (and so a rule's `help()` and `fix_title()` don't fight for the same field).
    pub fix_title: Option<&'static str>,
}

/// A collection of lint diagnostics for a single file.
///
/// The source is held once, behind an [`Arc`], and shared with every
/// diagnostic at render time.
#[derive(Debug, Clone)]
pub struct FileDiagnostics {
    /// The source code of the file.
    pub source_code: NamedSource<Arc<str>>,
    /// All diagnostics found in this file.
    pub diagnostics: Vec<LintDiagnostic>,
}

impl FileDiagnostics {
    /// Create a new `FileDiagnostics` from source code and diagnostics.
    #[must_use]
    pub fn new(
        name: impl AsRef<str>,
        source: impl Into<Arc<str>>,
        diagnostics: Vec<LintDiagnostic>,
    ) -> Self {
        Self {
            source_code: NamedSource::new(name, source.into()),
            diagnostics,
        }
    }

    /// Create a new empty `FileDiagnostics`.
    ///
    /// The empty source is shared: this is on the path of every clean file.
    #[must_use]
    pub fn empty() -> Self {
        static EMPTY: LazyLock<Arc<str>> = LazyLock::new(|| Arc::from(""));
        Self {
            source_code: NamedSource::new("", Arc::clone(&EMPTY)),
            diagnostics: Vec::new(),
        }
    }

    /// Returns true if there are no diagnostics.
    #[must_use]
    pub const fn is_empty(&self) -> bool {
        self.diagnostics.is_empty()
    }

    /// Returns the number of diagnostics.
    #[must_use]
    pub const fn len(&self) -> usize {
        self.diagnostics.len()
    }

    /// Each diagnostic paired with the file's source, ready to render on its own.
    pub fn reports(&self) -> impl Iterator<Item = Report> + '_ {
        self.diagnostics.iter().map(|diagnostic| {
            Report::new(diagnostic.clone()).with_source_code(self.source_code.clone())
        })
    }

    /// Render each diagnostic as a standalone block, propagating `handler` errors.
    pub fn render(&self, handler: &GraphicalReportHandler, out: &mut String) -> fmt::Result {
        self.reports()
            .try_for_each(|report| handler.render_report(out, report.as_ref()))
    }
}

/// Check the AST for lint errors.
///
/// Traverses the AST and runs all enabled lint rules, returning any diagnostics found.
///
/// `path` enables path-aware rules; pass [`None`] when linting a buffer without a backing file.
#[must_use]
pub fn check_ast<'a>(
    source: &'a str,
    ast: &Root<'a>,
    settings: &'a Settings,
    path: Option<&'a Path>,
) -> Vec<LintDiagnostic> {
    let mut checker = Checker::new(source, settings, path);
    checker.visit_root(ast);

    // The directive rules run before suppression so a `file-ignore[...]` silences them too;
    // the unused-code rule runs after, since it needs to know what was silenced.
    let mut ignore_comments = suppression::collect_ignore_comments(ast, &checker);
    checker.visit_ignore_comments(&ignore_comments);
    suppression::drop_ignored_diagnostics(&checker, &mut ignore_comments);
    checker.visit_unused_ignore_codes(&ignore_comments);
    checker.into_diagnostics()
}

/// Parse `source`, treating each of `custom_blocks` as a `{% tag %}...{% endtag %}` block.
///
/// The single door to the parser: every consumer (check, fix, playground,
/// benches, tests) must parse with the same configuration or lint on a
/// different AST than the one the formatter sees.
pub fn parse<'a>(
    source: &'a str,
    language: Language,
    custom_blocks: &[String],
) -> Result<Root<'a>, SyntaxError> {
    Parser::new(source, language, custom_blocks.to_vec()).parse_root()
}

/// Parse and lint `source` in one call.
///
/// `path` is forwarded to path-aware rules; pass [`None`] when there is no backing file.
pub fn lint_source(
    source: &str,
    language: Language,
    custom_blocks: &[String],
    settings: &Settings,
    path: Option<&Path>,
) -> Result<Vec<LintDiagnostic>, SyntaxError> {
    let ast = parse(source, language, custom_blocks)?;
    Ok(check_ast(source, &ast, settings, path))
}
