[package]
name = "djangofmt-fuzz"
version = "0.0.0"
edition = "2024"
publish = false

[package.metadata]
cargo-fuzz = true

[[bin]]
bench = false
doc = false
name = "fmt_idempotency"
path = "fuzz_targets/fmt_idempotency.rs"
test = false

[dependencies]
djangofmt_formatter = { path = "../crates/djangofmt_formatter" }
djangofmt_syntax = { path = "../crates/djangofmt_syntax" }
libfuzzer-sys = "0.4"
similar-asserts = "2.0.0"

[profile.release]
debug = 1
