//! Mode dispatch shared by every generator subcommand.

use std::fs;
use std::path::Path;

use anyhow::{Context, Result};
use djangofmt::fs::relativize_path;

use crate::{generate_docs, generate_rules_table};

pub const AUTOGEN_HEADER: &str = "<!-- WARNING: This file is auto-generated by `cargo run -p djangofmt_dev -- generate-all`. Do not edit. -->\n\n";

#[derive(clap::Args)]
pub struct Args {
    #[arg(long, default_value_t, value_enum)]
    pub mode: Mode,
}

#[derive(Copy, Clone, PartialEq, Eq, clap::ValueEnum, Default)]
pub enum Mode {
    /// Write the generated content to disk.
    #[default]
    Write,
    /// Print the generated content to stdout without touching the filesystem.
    DryRun,
}

/// Apply `content` to `path` according to `mode`.
pub fn apply(mode: Mode, path: &Path, content: &str) -> Result<()> {
    let display = relativize_path(path);
    match mode {
        Mode::Write => {
            if let Some(parent) = path.parent() {
                fs::create_dir_all(parent).with_context(|| {
                    format!("failed to create directory {}", relativize_path(parent))
                })?;
            }
            fs::write(path, content).with_context(|| format!("failed to write {display}"))?;
            eprintln!("Wrote {display}");
        }
        Mode::DryRun => {
            println!("===== {display} =====");
            println!("{content}");
        }
    }
    Ok(())
}

pub fn main(args: &Args) -> Result<()> {
    generate_docs::main(args)?;
    generate_rules_table::main(args)?;
    Ok(())
}
