pub mod django_static_url;
pub mod django_url_pattern;
pub mod duplicate_attr;
pub mod empty_tag_pair;
pub mod invalid_ignore_code;
pub mod invalid_ignore_comment;
pub mod javascript_url;
pub mod unused_ignore_code;
pub mod use_https;
