//! Enumerated attributes from `@markuplint/html-spec` 5.0.1.
//! Generated by `just html-spec`, do not edit.
//!
//! Copyright (c) 2017-2024 Yusuke Hirao, MIT License.

use super::{Attr, EnumAttr};

pub static ATTRS: &[Attr] = &[
    Attr {
        name: "accept-charset",
        elements: &[("form", Some(&FORM_ACCEPT_CHARSET))],
        global: None,
    },
    Attr {
        name: "autocapitalize",
        elements: &[],
        global: Some(&AUTOCAPITALIZE),
    },
    Attr {
        name: "autocomplete",
        elements: &[("form", Some(&FORM_AUTOCOMPLETE))],
        global: None,
    },
    Attr {
        name: "autocorrect",
        elements: &[],
        global: Some(&AUTOCORRECT),
    },
    Attr {
        name: "closedby",
        elements: &[("dialog", Some(&DIALOG_CLOSEDBY))],
        global: None,
    },
    Attr {
        name: "contenteditable",
        elements: &[],
        global: Some(&CONTENTEDITABLE),
    },
    Attr {
        name: "crossorigin",
        elements: &[
            ("audio", Some(&CROSSORIGIN)),
            ("img", Some(&CROSSORIGIN)),
            ("link", Some(&CROSSORIGIN)),
            ("video", Some(&CROSSORIGIN)),
        ],
        global: None,
    },
    Attr {
        name: "decoding",
        elements: &[("img", Some(&IMG_DECODING))],
        global: None,
    },
    Attr {
        name: "dir",
        elements: &[("bdo", Some(&BDO_DIR))],
        global: Some(&DIR),
    },
    Attr {
        name: "draggable",
        elements: &[],
        global: Some(&DRAGGABLE),
    },
    Attr {
        name: "enctype",
        elements: &[("form", Some(&FORM_ENCTYPE))],
        global: None,
    },
    Attr {
        name: "enterkeyhint",
        elements: &[],
        global: Some(&ENTERKEYHINT),
    },
    Attr {
        name: "fetchpriority",
        elements: &[
            ("iframe", Some(&FETCHPRIORITY)),
            ("img", Some(&FETCHPRIORITY)),
            ("link", Some(&FETCHPRIORITY)),
        ],
        global: None,
    },
    Attr {
        name: "formenctype",
        elements: &[
            ("button", Some(&FORMENCTYPE)),
            ("input", Some(&FORMENCTYPE)),
        ],
        global: None,
    },
    Attr {
        name: "formmethod",
        elements: &[("button", Some(&FORMMETHOD)), ("input", Some(&FORMMETHOD))],
        global: None,
    },
    Attr {
        name: "hidden",
        elements: &[],
        global: Some(&HIDDEN),
    },
    Attr {
        name: "inputmode",
        elements: &[],
        global: Some(&INPUTMODE),
    },
    Attr {
        name: "kind",
        elements: &[("track", Some(&TRACK_KIND))],
        global: None,
    },
    Attr {
        name: "loading",
        elements: &[
            ("audio", Some(&LOADING)),
            ("iframe", Some(&LOADING)),
            ("img", Some(&LOADING)),
            ("video", Some(&LOADING)),
        ],
        global: None,
    },
    Attr {
        name: "method",
        elements: &[("form", Some(&FORM_METHOD))],
        global: None,
    },
    Attr {
        name: "popover",
        elements: &[],
        global: Some(&POPOVER),
    },
    Attr {
        name: "popovertargetaction",
        elements: &[("button", Some(&BUTTON_POPOVERTARGETACTION))],
        global: None,
    },
    Attr {
        name: "preload",
        elements: &[("audio", Some(&PRELOAD)), ("video", Some(&PRELOAD))],
        global: None,
    },
    Attr {
        name: "scope",
        elements: &[("th", Some(&TH_SCOPE))],
        global: None,
    },
    Attr {
        name: "shadowrootmode",
        elements: &[("template", Some(&TEMPLATE_SHADOWROOTMODE))],
        global: None,
    },
    Attr {
        name: "shadowrootslotassignment",
        elements: &[("template", Some(&TEMPLATE_SHADOWROOTSLOTASSIGNMENT))],
        global: None,
    },
    Attr {
        name: "shape",
        elements: &[("area", Some(&AREA_SHAPE))],
        global: None,
    },
    Attr {
        name: "spellcheck",
        elements: &[],
        global: Some(&SPELLCHECK),
    },
    Attr {
        name: "translate",
        elements: &[],
        global: Some(&TRANSLATE),
    },
    Attr {
        name: "type",
        elements: &[
            ("button", Some(&BUTTON_TYPE)),
            ("input", Some(&INPUT_TYPE)),
            ("ol", Some(&OL_TYPE)),
        ],
        global: None,
    },
    Attr {
        name: "wrap",
        elements: &[("textarea", Some(&TEXTAREA_WRAP))],
        global: None,
    },
    Attr {
        name: "writingsuggestions",
        elements: &[],
        global: Some(&WRITINGSUGGESTIONS),
    },
    Attr {
        name: "xml:space",
        elements: &[],
        global: Some(&XML_SPACE),
    },
];

pub static HTML_GLOBAL_ATTR_TAGS: &[&str] = &[
    "a",
    "abbr",
    "address",
    "area",
    "article",
    "aside",
    "audio",
    "b",
    "base",
    "bdi",
    "bdo",
    "blockquote",
    "body",
    "br",
    "button",
    "canvas",
    "caption",
    "cite",
    "code",
    "col",
    "colgroup",
    "data",
    "datalist",
    "dd",
    "del",
    "details",
    "dfn",
    "dialog",
    "div",
    "dl",
    "dt",
    "em",
    "embed",
    "fieldset",
    "figcaption",
    "figure",
    "font",
    "footer",
    "form",
    "h1",
    "h2",
    "h3",
    "h4",
    "h5",
    "h6",
    "head",
    "header",
    "hgroup",
    "hr",
    "html",
    "i",
    "iframe",
    "img",
    "input",
    "ins",
    "kbd",
    "label",
    "legend",
    "li",
    "link",
    "main",
    "map",
    "mark",
    "menu",
    "meta",
    "meter",
    "nav",
    "noscript",
    "object",
    "ol",
    "optgroup",
    "option",
    "output",
    "p",
    "picture",
    "pre",
    "progress",
    "q",
    "rp",
    "rt",
    "ruby",
    "s",
    "samp",
    "script",
    "search",
    "section",
    "select",
    "slot",
    "small",
    "source",
    "span",
    "strong",
    "style",
    "sub",
    "summary",
    "sup",
    "table",
    "tbody",
    "td",
    "template",
    "textarea",
    "tfoot",
    "th",
    "thead",
    "time",
    "title",
    "tr",
    "track",
    "u",
    "ul",
    "var",
    "video",
    "wbr",
];

static AREA_SHAPE: EnumAttr = EnumAttr {
    values: &["rect", "circle", "poly", "default"],
    case_insensitive: true,
};
static AUTOCAPITALIZE: EnumAttr = EnumAttr {
    values: &["off", "on", "none", "sentences", "words", "characters"],
    case_insensitive: true,
};
static AUTOCORRECT: EnumAttr = EnumAttr {
    values: &["", "on", "off"],
    case_insensitive: true,
};
static BDO_DIR: EnumAttr = EnumAttr {
    values: &["ltr", "rtl"],
    case_insensitive: true,
};
static BUTTON_POPOVERTARGETACTION: EnumAttr = EnumAttr {
    values: &["toggle", "show", "hide"],
    case_insensitive: true,
};
static BUTTON_TYPE: EnumAttr = EnumAttr {
    values: &["submit", "reset", "button"],
    case_insensitive: true,
};
static CONTENTEDITABLE: EnumAttr = EnumAttr {
    values: &["", "true", "false", "plaintext-only"],
    case_insensitive: true,
};
static CROSSORIGIN: EnumAttr = EnumAttr {
    values: &["", "anonymous", "use-credentials"],
    case_insensitive: true,
};
static DIALOG_CLOSEDBY: EnumAttr = EnumAttr {
    values: &["any", "closerequest", "none"],
    case_insensitive: true,
};
static DIR: EnumAttr = EnumAttr {
    values: &["ltr", "rtl", "auto"],
    case_insensitive: true,
};
static DRAGGABLE: EnumAttr = EnumAttr {
    values: &["true", "false"],
    case_insensitive: true,
};
static ENTERKEYHINT: EnumAttr = EnumAttr {
    values: &["enter", "done", "go", "next", "previous", "search", "send"],
    case_insensitive: true,
};
static FETCHPRIORITY: EnumAttr = EnumAttr {
    values: &["high", "low", "auto"],
    case_insensitive: true,
};
static FORMENCTYPE: EnumAttr = EnumAttr {
    values: &[
        "application/x-www-form-urlencoded",
        "multipart/form-data",
        "text/plain",
    ],
    case_insensitive: true,
};
static FORMMETHOD: EnumAttr = EnumAttr {
    values: &["post", "get", "dialog"],
    case_insensitive: true,
};
static FORM_ACCEPT_CHARSET: EnumAttr = EnumAttr {
    values: &["utf-8"],
    case_insensitive: true,
};
static FORM_AUTOCOMPLETE: EnumAttr = EnumAttr {
    values: &["on", "off"],
    case_insensitive: true,
};
static FORM_ENCTYPE: EnumAttr = EnumAttr {
    values: &[
        "application/x-www-form-urlencoded",
        "multipart/form-data",
        "text/plain",
    ],
    case_insensitive: true,
};
static FORM_METHOD: EnumAttr = EnumAttr {
    values: &["post", "get", "dialog"],
    case_insensitive: true,
};
static HIDDEN: EnumAttr = EnumAttr {
    values: &["", "hidden", "until-found"],
    case_insensitive: true,
};
static IMG_DECODING: EnumAttr = EnumAttr {
    values: &["sync", "async", "auto"],
    case_insensitive: true,
};
static INPUTMODE: EnumAttr = EnumAttr {
    values: &[
        "none", "text", "tel", "url", "email", "numeric", "decimal", "search",
    ],
    case_insensitive: true,
};
static INPUT_TYPE: EnumAttr = EnumAttr {
    values: &[
        "hidden",
        "text",
        "search",
        "tel",
        "url",
        "email",
        "password",
        "date",
        "month",
        "week",
        "time",
        "datetime-local",
        "number",
        "range",
        "color",
        "checkbox",
        "radio",
        "file",
        "submit",
        "image",
        "reset",
        "button",
    ],
    case_insensitive: true,
};
static LOADING: EnumAttr = EnumAttr {
    values: &["lazy", "eager"],
    case_insensitive: true,
};
static OL_TYPE: EnumAttr = EnumAttr {
    values: &["1", "a", "A", "i", "I"],
    case_insensitive: false,
};
static POPOVER: EnumAttr = EnumAttr {
    values: &["", "auto", "manual", "hint"],
    case_insensitive: true,
};
static PRELOAD: EnumAttr = EnumAttr {
    values: &["none", "metadata", "auto"],
    case_insensitive: true,
};
static SPELLCHECK: EnumAttr = EnumAttr {
    values: &["", "true", "false"],
    case_insensitive: true,
};
static TEMPLATE_SHADOWROOTMODE: EnumAttr = EnumAttr {
    values: &["open", "closed"],
    case_insensitive: true,
};
static TEMPLATE_SHADOWROOTSLOTASSIGNMENT: EnumAttr = EnumAttr {
    values: &["named", "manual"],
    case_insensitive: true,
};
static TEXTAREA_WRAP: EnumAttr = EnumAttr {
    values: &["soft", "hard"],
    case_insensitive: true,
};
static TH_SCOPE: EnumAttr = EnumAttr {
    values: &["row", "col", "rowgroup", "colgroup"],
    case_insensitive: true,
};
static TRACK_KIND: EnumAttr = EnumAttr {
    values: &[
        "subtitles",
        "captions",
        "descriptions",
        "chapters",
        "metadata",
    ],
    case_insensitive: true,
};
static TRANSLATE: EnumAttr = EnumAttr {
    values: &["", "yes", "no"],
    case_insensitive: true,
};
static WRITINGSUGGESTIONS: EnumAttr = EnumAttr {
    values: &["", "true", "false"],
    case_insensitive: true,
};
static XML_SPACE: EnumAttr = EnumAttr {
    values: &["default", "preserve"],
    case_insensitive: true,
};
