//! Enumerated attributes from `@markuplint/html-spec` 5.0.1.
//! Generated by `just html-spec`, do not edit.
//!
//! Copyright (c) 2017-2024 Yusuke Hirao, MIT License.

use super::Attr;

pub static ATTRS: &[Attr] = &[
    Attr {
        name: "accept-charset",
        elements: &[("form", FORM_ACCEPT_CHARSET)],
        global: None,
    },
    Attr {
        name: "autocapitalize",
        elements: &[],
        global: Some(AUTOCAPITALIZE),
    },
    Attr {
        name: "autocomplete",
        elements: &[("form", FORM_AUTOCOMPLETE)],
        global: None,
    },
    Attr {
        name: "autocorrect",
        elements: &[],
        global: Some(AUTOCORRECT),
    },
    Attr {
        name: "closedby",
        elements: &[("dialog", DIALOG_CLOSEDBY)],
        global: None,
    },
    Attr {
        name: "contenteditable",
        elements: &[],
        global: Some(CONTENTEDITABLE),
    },
    Attr {
        name: "crossorigin",
        elements: &[
            ("audio", CROSSORIGIN),
            ("img", CROSSORIGIN),
            ("link", CROSSORIGIN),
            ("video", CROSSORIGIN),
        ],
        global: None,
    },
    Attr {
        name: "decoding",
        elements: &[("img", IMG_DECODING)],
        global: None,
    },
    Attr {
        name: "dir",
        elements: &[("bdo", BDO_DIR)],
        global: Some(DIR),
    },
    Attr {
        name: "draggable",
        elements: &[],
        global: Some(DRAGGABLE),
    },
    Attr {
        name: "enctype",
        elements: &[("form", FORM_ENCTYPE)],
        global: None,
    },
    Attr {
        name: "enterkeyhint",
        elements: &[],
        global: Some(ENTERKEYHINT),
    },
    Attr {
        name: "fetchpriority",
        elements: &[
            ("iframe", FETCHPRIORITY),
            ("img", FETCHPRIORITY),
            ("link", FETCHPRIORITY),
        ],
        global: None,
    },
    Attr {
        name: "formenctype",
        elements: &[("button", FORMENCTYPE), ("input", FORMENCTYPE)],
        global: None,
    },
    Attr {
        name: "formmethod",
        elements: &[("button", FORMMETHOD), ("input", FORMMETHOD)],
        global: None,
    },
    Attr {
        name: "hidden",
        elements: &[],
        global: Some(HIDDEN),
    },
    Attr {
        name: "inputmode",
        elements: &[],
        global: Some(INPUTMODE),
    },
    Attr {
        name: "kind",
        elements: &[("track", TRACK_KIND)],
        global: None,
    },
    Attr {
        name: "loading",
        elements: &[
            ("audio", LOADING),
            ("iframe", LOADING),
            ("img", LOADING),
            ("video", LOADING),
        ],
        global: None,
    },
    Attr {
        name: "method",
        elements: &[("form", FORM_METHOD)],
        global: None,
    },
    Attr {
        name: "popover",
        elements: &[],
        global: Some(POPOVER),
    },
    Attr {
        name: "popovertargetaction",
        elements: &[("button", BUTTON_POPOVERTARGETACTION)],
        global: None,
    },
    Attr {
        name: "preload",
        elements: &[("audio", PRELOAD), ("video", PRELOAD)],
        global: None,
    },
    Attr {
        name: "scope",
        elements: &[("th", TH_SCOPE)],
        global: None,
    },
    Attr {
        name: "shadowrootmode",
        elements: &[("template", TEMPLATE_SHADOWROOTMODE)],
        global: None,
    },
    Attr {
        name: "shadowrootslotassignment",
        elements: &[("template", TEMPLATE_SHADOWROOTSLOTASSIGNMENT)],
        global: None,
    },
    Attr {
        name: "shape",
        elements: &[("area", AREA_SHAPE)],
        global: None,
    },
    Attr {
        name: "spellcheck",
        elements: &[],
        global: Some(SPELLCHECK),
    },
    Attr {
        name: "translate",
        elements: &[],
        global: Some(TRANSLATE),
    },
    Attr {
        name: "type",
        elements: &[
            ("button", BUTTON_TYPE),
            ("input", INPUT_TYPE),
            ("ol", OL_TYPE),
        ],
        global: None,
    },
    Attr {
        name: "wrap",
        elements: &[("textarea", TEXTAREA_WRAP)],
        global: None,
    },
    Attr {
        name: "writingsuggestions",
        elements: &[],
        global: Some(WRITINGSUGGESTIONS),
    },
    Attr {
        name: "xml:space",
        elements: &[],
        global: Some(XML_SPACE),
    },
];

pub static HTML_GLOBAL_ATTR_TAGS: &[&str] = &[
    "a",
    "abbr",
    "address",
    "area",
    "article",
    "aside",
    "audio",
    "b",
    "base",
    "bdi",
    "bdo",
    "blockquote",
    "body",
    "br",
    "button",
    "canvas",
    "caption",
    "cite",
    "code",
    "col",
    "colgroup",
    "data",
    "datalist",
    "dd",
    "del",
    "details",
    "dfn",
    "dialog",
    "div",
    "dl",
    "dt",
    "em",
    "embed",
    "fieldset",
    "figcaption",
    "figure",
    "font",
    "footer",
    "form",
    "h1",
    "h2",
    "h3",
    "h4",
    "h5",
    "h6",
    "head",
    "header",
    "hgroup",
    "hr",
    "html",
    "i",
    "iframe",
    "img",
    "input",
    "ins",
    "kbd",
    "label",
    "legend",
    "li",
    "link",
    "main",
    "map",
    "mark",
    "menu",
    "meta",
    "meter",
    "nav",
    "noscript",
    "object",
    "ol",
    "optgroup",
    "option",
    "output",
    "p",
    "picture",
    "pre",
    "progress",
    "q",
    "rp",
    "rt",
    "ruby",
    "s",
    "samp",
    "script",
    "search",
    "section",
    "select",
    "slot",
    "small",
    "source",
    "span",
    "strong",
    "style",
    "sub",
    "summary",
    "sup",
    "table",
    "tbody",
    "td",
    "template",
    "textarea",
    "tfoot",
    "th",
    "thead",
    "time",
    "title",
    "tr",
    "track",
    "u",
    "ul",
    "var",
    "video",
    "wbr",
];

static AREA_SHAPE: &[&str] = &["rect", "circle", "poly", "default"];
static AUTOCAPITALIZE: &[&str] = &["off", "on", "none", "sentences", "words", "characters"];
static AUTOCORRECT: &[&str] = &["", "on", "off"];
static BDO_DIR: &[&str] = &["ltr", "rtl"];
static BUTTON_POPOVERTARGETACTION: &[&str] = &["toggle", "show", "hide"];
static BUTTON_TYPE: &[&str] = &["submit", "reset", "button"];
static CONTENTEDITABLE: &[&str] = &["", "true", "false", "plaintext-only"];
static CROSSORIGIN: &[&str] = &["", "anonymous", "use-credentials"];
static DIALOG_CLOSEDBY: &[&str] = &["any", "closerequest", "none"];
static DIR: &[&str] = &["ltr", "rtl", "auto"];
static DRAGGABLE: &[&str] = &["true", "false"];
static ENTERKEYHINT: &[&str] = &["enter", "done", "go", "next", "previous", "search", "send"];
static FETCHPRIORITY: &[&str] = &["high", "low", "auto"];
static FORMENCTYPE: &[&str] = &[
    "application/x-www-form-urlencoded",
    "multipart/form-data",
    "text/plain",
];
static FORMMETHOD: &[&str] = &["post", "get", "dialog"];
static FORM_ACCEPT_CHARSET: &[&str] = &["utf-8"];
static FORM_AUTOCOMPLETE: &[&str] = &["on", "off"];
static FORM_ENCTYPE: &[&str] = &[
    "application/x-www-form-urlencoded",
    "multipart/form-data",
    "text/plain",
];
static FORM_METHOD: &[&str] = &["post", "get", "dialog"];
static HIDDEN: &[&str] = &["", "hidden", "until-found"];
static IMG_DECODING: &[&str] = &["sync", "async", "auto"];
static INPUTMODE: &[&str] = &[
    "none", "text", "tel", "url", "email", "numeric", "decimal", "search",
];
static INPUT_TYPE: &[&str] = &[
    "hidden",
    "text",
    "search",
    "tel",
    "url",
    "email",
    "password",
    "date",
    "month",
    "week",
    "time",
    "datetime-local",
    "number",
    "range",
    "color",
    "checkbox",
    "radio",
    "file",
    "submit",
    "image",
    "reset",
    "button",
];
static LOADING: &[&str] = &["lazy", "eager"];
static OL_TYPE: &[&str] = &["1", "a", "A", "i", "I"];
static POPOVER: &[&str] = &["", "auto", "manual", "hint"];
static PRELOAD: &[&str] = &["none", "metadata", "auto"];
static SPELLCHECK: &[&str] = &["", "true", "false"];
static TEMPLATE_SHADOWROOTMODE: &[&str] = &["open", "closed"];
static TEMPLATE_SHADOWROOTSLOTASSIGNMENT: &[&str] = &["named", "manual"];
static TEXTAREA_WRAP: &[&str] = &["soft", "hard"];
static TH_SCOPE: &[&str] = &["row", "col", "rowgroup", "colgroup"];
static TRACK_KIND: &[&str] = &[
    "subtitles",
    "captions",
    "descriptions",
    "chapters",
    "metadata",
];
static TRANSLATE: &[&str] = &["", "yes", "no"];
static WRITINGSUGGESTIONS: &[&str] = &["", "true", "false"];
static XML_SPACE: &[&str] = &["default", "preserve"];
