# Run `cargo bloat` for finding out what takes most of the space in your executable.
name: Cargo Bloat

on:
  workflow_dispatch:
    inputs:
      branch:
        description: "Branch name"
        required: true
        default: "main"

permissions: {}

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  bloat:
    name: Cargo Bloat
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          ref: ${{ github.event.inputs.branch }}
          persist-credentials: false
      - uses: cargo-bins/cargo-binstall@75b4bfae1b2c753a6806bbce6e6cb89b602de33c # v1.22.0
      - run: cargo binstall --no-confirm cargo-bloat
      - name: Run
        env:
          RUSTFLAGS: "-C debuginfo=2 -C strip=none"
        shell: bash
        run: |
          {
            echo "# Bloat Summary"
            echo
            echo "## Largest functions"
            echo '```'
            echo
            cargo bloat --release -p djangofmt -n 15 2> /dev/null
            echo
            echo '```'
            echo
            echo "## Largest crates"
            echo '```'
            echo
            cargo bloat --release -p djangofmt --crates -n 15 2> /dev/null
            echo
            echo '```'
          } >> "$GITHUB_STEP_SUMMARY"
