name: CI

on:
  pull_request:
  push:
    branches:
      - main
    tags:
      - "**"

permissions: {}

concurrency:
  group: ${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

env:
  CARGO_TERM_COLOR: always
  UV_VERSION: 0.9.13
  # Make sure CI fails on all warnings, including Clippy lints
  RUSTFLAGS: "-Dwarnings"

jobs:
  changed_files:
    name: "Determine which files changed"
    runs-on: ubuntu-24.04
    permissions:
      contents: read
    outputs:
      code: ${{ steps.changed.outputs.code_any_changed }}
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          persist-credentials: true

      - uses: tj-actions/changed-files@22103cc46bda19c2b464ffe86db46df6922fd323 # v47.0.5
        id: changed
        with:
          files_yaml: |
            code:
              - python/**
              - crates/**
              - .github/workflows/ci.yml
              - Cargo.toml

  build-and-compare:
    name: "Ecosystem check"
    runs-on: ubuntu-24.04
    needs: changed_files
    if: ${{ github.event_name == 'pull_request' && needs.changed_files.outputs.code == 'true' }}
    permissions:
      contents: read
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          ref: main
          persist-credentials: false
      - name: Build main version
        run: cargo build -p djangofmt --release --verbose && mv target/release/djangofmt ./main_djangofmt

      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          persist-credentials: false
          clean: false

      - name: Build PR version
        run: cargo build -p djangofmt --release --verbose && mv target/release/djangofmt ./pr_djangofmt

      - name: Setup uv
        uses: astral-sh/setup-uv@37802adc94f370d6bfd71619e3f0bf239e1f3b78 # v7.6.0
        with:
          enable-cache: false

      - name: Install rustywind
        run: npm install -g rustywind

      - name: Run `djangofmt` ecosystem check
        run: |
          # Set pipefail to avoid hiding errors with tee
          set -eo pipefail

          uv venv --python 3.12
          uv pip install ./python/ecosystem-check

          printf "### \`pr\` vs \`main\` diff\n" >> ecosystem-result-format-stable
          uv run ecosystem-check format ./main_djangofmt ./pr_djangofmt --cache-dir ./checkouts | tee -a ecosystem-result-format-stable

          printf "\n### \`pr\` stability\n" >> ecosystem-result-format-stable
          uv run ecosystem-check format ./pr_djangofmt ./pr_djangofmt --cache-dir ./checkouts --format-comparison base-then-comp | tee -a ecosystem-result-format-stable

          printf "\n### \`pr\` + \`rustywind\` stability\n" >> ecosystem-result-format-stable
          uv run ecosystem-check format rustywind ./pr_djangofmt  --cache-dir ./checkouts --format-comparison base-then-comp-converge | tee -a ecosystem-result-format-stable

          printf "\n### \`pr\` + \`djade\` stability\n" >> ecosystem-result-format-stable
          uv run ecosystem-check format djade ./pr_djangofmt --cache-dir ./checkouts --format-comparison base-then-comp-converge | tee -a ecosystem-result-format-stable

          if [ "$(stat -c%s "ecosystem-result-format-stable")" -gt 1024000 ]; then
            echo -e "\n\n> [!CAUTION]\n> **Summary Truncated:** The original output was $(du -h ecosystem-result-format-stable | cut -f1), which exceeds GitHub's 1024k limit." >> "$GITHUB_STEP_SUMMARY"
          fi

          head -c 1000k ecosystem-result-format-stable >> "$GITHUB_STEP_SUMMARY"

          cat ecosystem-result-format-stable >> ecosystem-result

      - name: Generate comment content
        id: generate-comment
        run: |
          # Note this identifier is used to find the comment to update on subsequent runs
          echo '<!-- generated-comment ecosystem -->' >> placeholder-comment.txt

          {
            cat placeholder-comment.txt
            echo "## \`ecosystem-check\` results"
            cat ecosystem-result
          } >> full-comment.txt

          # Determine if the comment exceeds 65536 characters
          char_count=$(wc -c < full-comment.txt)
          if [ "$char_count" -gt 65536 ]; then
              {
                cat placeholder-comment.txt
                echo "## \`ecosystem-check\` results (partial, see full diff [here](${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}))"
                cat ecosystem-result
              } > full-comment.txt
          fi

      - name: Upload ecosystem result
        uses: actions/upload-artifact@bbbca2ddaa5d8feaa63e36b76fdaad77386f024f # v7.0.0
        with:
          name: ecosystem-result
          path: full-comment.txt

      - name: Store pr-number
        run: |
          echo ${{ github.event.number }} > pr-number

      - name: Upload pr-number
        uses: actions/upload-artifact@bbbca2ddaa5d8feaa63e36b76fdaad77386f024f # v7.0.0
        with:
          name: pr-number
          path: pr-number

  clippy_check:
    name: "cargo clippy"
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          persist-credentials: false
      - name: Install Rust toolchain
        run: rustup component add clippy
      - name: Run Clippy
        run: cargo clippy --all-targets --all-features

  cargo-shear:
    name: "cargo shear"
    runs-on: ubuntu-24.04
    needs: changed_files
    if: ${{ needs.changed_files.outputs.code == 'true' || github.ref == 'refs/heads/main' }}
    permissions:
      contents: read
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          persist-credentials: false
      - uses: cargo-bins/cargo-binstall@113a77a4ce971c41332f2129c3d995df993cf746 # v1.17.8
      - run: cargo binstall --no-confirm cargo-shear
      - run: cargo shear

  test:
    name: "cargo test"
    runs-on: ubuntu-24.04
    needs: changed_files
    if: ${{ needs.changed_files.outputs.code == 'true' || github.ref == 'refs/heads/main' }}
    permissions:
      contents: read
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          persist-credentials: false
      - run: cargo build
      - run: cargo test
