name: Ecosystem check

on:
  pull_request:
  push:
    branches:
      - main
    tags:
      - "**"

permissions:
  contents: read

concurrency:
  group: ${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

env:
  CARGO_TERM_COLOR: always
  UV_VERSION: 0.1.23

jobs:
  build-and-compare:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4
        with:
          persist-credentials: false

      - name: Build PR version
        run: cargo build --release --verbose && mv target/release/djangofmt ./pr_build

      - uses: actions/checkout@v4
        with:
          ref: main
          persist-credentials: false
          clean: false

      - name: Build main version
        run: cargo build --release --verbose && mv target/release/djangofmt ./main_build

      - name: Setup uv
        uses: astral-sh/setup-uv@v5
        with:
          enable-cache: false

      - name: Run `djangofmt` ecosystem check
        run: |
          # Set pipefail to avoid hiding errors with tee
          set -eo pipefail

          uv venv --python 3.12
          uv pip install ./python/ecosystem-check
          uv run ecosystem-check format ./main_build ./pr_build --cache ./checkouts --output-format markdown | tee ecosystem-result-format-stable

          cat ecosystem-result-format-stable > "$GITHUB_STEP_SUMMARY"
          {
            echo "### Formatter (stable)"
            cat ecosystem-result-format-stable
            echo ""
          } >> ecosystem-result
