# Publish a release to PyPI.
#
# Should be part of `publish-jobs` in `dist-workspace.toml` configuration.
# See https://opensource.axo.dev/cargo-dist/book/reference/config.html#publish-jobs
name: "[djangofmt] Publish to PyPI"

on:
  workflow_call:
    inputs:
      plan:
        required: true
        type: string

jobs:
  pypi-publish:
    name: Upload to PyPI
    runs-on: ubuntu-24.04
    environment:
      name: release
    permissions:
      # For PyPI's trusted publishing.
      id-token: write
    env:
      UV_PUBLISH_USERNAME: ${{ vars.UV_PUBLISH_USERNAME }}
      UV_PUBLISH_PASSWORD: ${{ secrets.UV_PUBLISH_PASSWORD }}
      UV_PUBLISH_URL: ${{ vars.UV_PUBLISH_URL }}
    steps:
      - name: "Install uv"
        uses: astral-sh/setup-uv@85856786d1ce8acfbcc2f13a5f3fbd6b938f9f41 # v7.1.2
      - uses: actions/download-artifact@018cc2cf5baa6db3ef3c5f8a56943fffe632ef53 # v6.0.0
        with:
          pattern: wheels-*
          path: wheels
          merge-multiple: true
      - name: Publish to PyPi
        run: uv publish -v wheels/*
