# Publish a release to PyPI.
#
# Should be part of `publish-jobs` in `dist-workspace.toml` configuration.
# See https://opensource.axo.dev/cargo-dist/book/reference/config.html#publish-jobs
name: "[djangofmt] Publish to PyPI"

on:
  workflow_call:
    inputs:
      plan:
        required: true
        type: string

jobs:
  pypi-publish:
    name: Upload to PyPI
    runs-on: ubuntu-24.04
    environment:
      name: release
    permissions:
      # For PyPI's trusted publishing.
      id-token: write
    steps:
      - name: "Install uv"
        uses: astral-sh/setup-uv@v5
      - uses: actions/download-artifact@v4
        with:
          pattern: wheels-*
          path: wheels
          merge-multiple: true
      - name: Publish to PyPi
        run: uv publish -v wheels/*
